// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/services/push_notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:firebase_core/firebase_core.dart' as _i5;
import 'package:firebase_messaging/firebase_messaging.dart' as _i14;
import 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart'
    as _i6;
import 'package:keycast_flutter/keycast_flutter.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:nostr_client/src/models/models.dart' as _i2;
import 'package:nostr_client/src/nostr_client.dart' as _i7;
import 'package:nostr_sdk/nostr_sdk.dart' as _i4;
import 'package:openvine/models/known_account.dart' as _i11;
import 'package:openvine/services/auth_service.dart' as _i3;
import 'package:openvine/services/notification_service.dart' as _i15;
import 'package:openvine/services/relay_discovery_service.dart' as _i10;
import 'package:openvine/services/user_profile_service.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCountResult_0 extends _i1.SmartFake implements _i2.CountResult {
  _FakeCountResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrConnectSession_2 extends _i1.SmartFake
    implements _i4.NostrConnectSession {
  _FakeNostrConnectSession_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_3 extends _i1.SmartFake implements _i5.FirebaseApp {
  _FakeFirebaseApp_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationSettings_4 extends _i1.SmartFake
    implements _i6.NotificationSettings {
  _FakeNotificationSettings_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NostrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrClient extends _i1.Mock implements _i7.NostrClient {
  MockNostrClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  int get activeSubscriptionCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionCount),
            returnValue: 0,
          )
          as int);

  @override
  List<String> get configuredRelays =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  int get configuredRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, _i2.RelayConnectionStatus> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, _i2.RelayConnectionStatus>{},
          )
          as Map<String, _i2.RelayConnectionStatus>);

  @override
  _i9.Stream<Map<String, _i2.RelayConnectionStatus>> get relayStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatusStream),
            returnValue:
                _i9.Stream<Map<String, _i2.RelayConnectionStatus>>.empty(),
          )
          as _i9.Stream<Map<String, _i2.RelayConnectionStatus>>);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  set statisticsObserver(_i7.NostrClientStatisticsObserver? value) =>
      super.noSuchMethod(
        Invocation.setter(#statisticsObserver, value),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.Event?> publishEvent(
    _i4.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishEvent,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Future<List<_i4.Event>> queryEvents(
    List<_i4.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #useCache: useCache,
              },
            ),
            returnValue: _i9.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i9.Future<List<_i4.Event>>);

  @override
  _i9.Future<_i2.CountResult> countEvents(
    List<_i4.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i9.Future<_i2.CountResult>.value(
              _FakeCountResult_0(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #subscriptionId: subscriptionId,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.CountResult>);

  @override
  _i9.Future<_i4.Event?> fetchEventById(
    String? eventId, {
    String? relayUrl,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {#relayUrl: relayUrl, #useCache: useCache},
            ),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Future<_i4.Event?> fetchProfile(
    String? pubkey, {
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, [pubkey], {#useCache: useCache}),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Stream<_i4.Event> subscribe(
    List<_i4.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i9.Stream<_i4.Event>.empty(),
          )
          as _i9.Stream<_i4.Event>);

  @override
  _i9.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<int> addRelays(List<String>? relayUrls) =>
      (super.noSuchMethod(
            Invocation.method(#addRelays, [relayUrls]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<bool> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  Map<String, ({int errors, int eventsReceived, int queriesSent})>
  getRelayPoolCounters() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayPoolCounters, []),
            returnValue:
                <String, ({int errors, int eventsReceived, int queriesSent})>{},
          )
          as Map<String, ({int errors, int eventsReceived, int queriesSent})>);

  @override
  _i9.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i9.Future<Map<String, dynamic>?>.value(),
          )
          as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<void> retryDisconnectedRelays() =>
      (super.noSuchMethod(
            Invocation.method(#retryDisconnectedRelays, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> forceReconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#forceReconnectAll, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i9.Future<_i4.Event?> sendLike(
    String? eventId, {
    String? content,
    String? addressableId,
    String? targetAuthorPubkey,
    int? targetKind,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [eventId],
              {
                #content: content,
                #addressableId: addressableId,
                #targetAuthorPubkey: targetAuthorPubkey,
                #targetKind: targetKind,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Future<_i4.Event?> sendProfile({
    required Map<String, dynamic>? profileContent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendProfile, [], {
              #profileContent: profileContent,
            }),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Future<_i4.Event?> sendRepost(
    String? eventId, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [eventId],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Future<_i4.Event?> sendGenericRepost({
    required String? addressableId,
    required int? targetKind,
    required String? authorPubkey,
    String? eventId,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendGenericRepost, [], {
              #addressableId: addressableId,
              #targetKind: targetKind,
              #authorPubkey: authorPubkey,
              #eventId: eventId,
              #content: content,
              #tempRelays: tempRelays,
              #targetRelays: targetRelays,
            }),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Future<_i4.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Future<_i4.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Future<_i4.Event?> sendContactList(
    _i4.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Stream<_i4.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i9.Stream<_i4.Event>.empty(),
          )
          as _i9.Stream<_i4.Event>);

  @override
  _i9.Stream<_i4.Event> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i9.Stream<_i4.Event>.empty(),
          )
          as _i9.Stream<_i4.Event>);

  @override
  _i9.Future<List<_i4.Event>> queryUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#queryUsers, [query], {#limit: limit}),
            returnValue: _i9.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i9.Future<List<_i4.Event>>);

  @override
  _i9.Future<String?> createNip98AuthHeader({
    required String? url,
    required String? method,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNip98AuthHeader, [], {
              #url: url,
              #method: method,
              #payload: payload,
            }),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i3.AuthState.unauthenticated,
          )
          as _i3.AuthState);

  @override
  _i9.Stream<_i3.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i9.Stream<_i3.AuthState>.empty(),
          )
          as _i9.Stream<_i3.AuthState>);

  @override
  _i9.Stream<_i3.UserProfile?> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i9.Stream<_i3.UserProfile?>.empty(),
          )
          as _i9.Stream<_i3.UserProfile?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i3.AuthenticationSource get authenticationSource =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationSource),
            returnValue: _i3.AuthenticationSource.none,
          )
          as _i3.AuthenticationSource);

  @override
  bool get isRegistered =>
      (super.noSuchMethod(Invocation.getter(#isRegistered), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  List<_i10.DiscoveredRelay> get userRelays =>
      (super.noSuchMethod(
            Invocation.getter(#userRelays),
            returnValue: <_i10.DiscoveredRelay>[],
          )
          as List<_i10.DiscoveredRelay>);

  @override
  bool get hasExistingProfile =>
      (super.noSuchMethod(
            Invocation.getter(#hasExistingProfile),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get serviceName =>
      (super.noSuchMethod(
            Invocation.getter(#serviceName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#serviceName),
            ),
          )
          as String);

  @override
  void registerUserRelaysDiscoveredCallback(
    _i3.UserRelaysDiscoveredCallback? callback,
  ) => super.noSuchMethod(
    Invocation.method(#registerUserRelaysDiscoveredCallback, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<bool> hasSavedKeys() =>
      (super.noSuchMethod(
            Invocation.method(#hasSavedKeys, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<String?> getSavedNpub() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedNpub, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewIdentity, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i9.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#createNewIdentity, [], {
                  #biometricPrompt: biometricPrompt,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.AuthResult>);

  @override
  _i9.Future<void> createAnonymousAccount() =>
      (super.noSuchMethod(
            Invocation.method(#createAnonymousAccount, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i11.KnownAccount>> getKnownAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getKnownAccounts, []),
            returnValue: _i9.Future<List<_i11.KnownAccount>>.value(
              <_i11.KnownAccount>[],
            ),
          )
          as _i9.Future<List<_i11.KnownAccount>>);

  @override
  _i9.Future<void> removeKnownAccount(String? pubkeyHex) =>
      (super.noSuchMethod(
            Invocation.method(#removeKnownAccount, [pubkeyHex]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> signInForAccount(
    String? pubkeyHex,
    _i3.AuthenticationSource? authSource,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInForAccount, [pubkeyHex, authSource]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.AuthResult> connectWithAmber() =>
      (super.noSuchMethod(
            Invocation.method(#connectWithAmber, []),
            returnValue: _i9.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#connectWithAmber, [])),
            ),
          )
          as _i9.Future<_i3.AuthResult>);

  @override
  _i9.Future<_i3.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromNsec,
              [nsec],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i9.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(
                  #importFromNsec,
                  [nsec],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i9.Future<_i3.AuthResult>);

  @override
  _i9.Future<_i3.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromHex,
              [privateKeyHex],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i9.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(
                  #importFromHex,
                  [privateKeyHex],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i9.Future<_i3.AuthResult>);

  @override
  _i9.Future<_i3.AuthResult> connectWithBunker(String? bunkerUrl) =>
      (super.noSuchMethod(
            Invocation.method(#connectWithBunker, [bunkerUrl]),
            returnValue: _i9.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#connectWithBunker, [bunkerUrl]),
              ),
            ),
          )
          as _i9.Future<_i3.AuthResult>);

  @override
  _i9.Future<_i4.NostrConnectSession> initiateNostrConnect({
    List<String>? customRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initiateNostrConnect, [], {
              #customRelays: customRelays,
            }),
            returnValue: _i9.Future<_i4.NostrConnectSession>.value(
              _FakeNostrConnectSession_2(
                this,
                Invocation.method(#initiateNostrConnect, [], {
                  #customRelays: customRelays,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.NostrConnectSession>);

  @override
  _i9.Future<_i3.AuthResult> waitForNostrConnectResponse({
    Duration? timeout = const Duration(minutes: 2),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForNostrConnectResponse, [], {
              #timeout: timeout,
            }),
            returnValue: _i9.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#waitForNostrConnectResponse, [], {
                  #timeout: timeout,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.AuthResult>);

  @override
  void cancelNostrConnect() => super.noSuchMethod(
    Invocation.method(#cancelNostrConnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void onSignerCallbackReceived() => super.noSuchMethod(
    Invocation.method(#onSignerCallbackReceived, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> refreshCurrentProfile(
    _i12.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> signInWithDivineOAuth(_i13.KeycastSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithDivineOAuth, [session]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<(bool, String?)> deleteKeycastAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteKeycastAccount, []),
            returnValue: _i9.Future<(bool, String?)>.value((false, null)),
          )
          as _i9.Future<(bool, String?)>);

  @override
  _i9.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<_i4.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
    int? createdAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
              #createdAt: createdAt,
            }),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Future<void> acceptTerms() =>
      (super.noSuchMethod(
            Invocation.method(#acceptTerms, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void onAppBackgrounded() => super.noSuchMethod(
    Invocation.method(#onAppBackgrounded, []),
    returnValueForMissingStub: null,
  );

  @override
  void onAppResumed() => super.noSuchMethod(
    Invocation.method(#onAppResumed, []),
    returnValueForMissingStub: null,
  );

  @override
  void onExtendedBackground() => super.noSuchMethod(
    Invocation.method(#onExtendedBackground, []),
    returnValueForMissingStub: null,
  );

  @override
  void onPeriodicCleanup() => super.noSuchMethod(
    Invocation.method(#onPeriodicCleanup, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [FirebaseMessaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessaging extends _i1.Mock implements _i14.FirebaseMessaging {
  MockFirebaseMessaging() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_3(this, Invocation.getter(#app)),
          )
          as _i5.FirebaseApp);

  @override
  bool get isAutoInitEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isAutoInitEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Stream<String> get onTokenRefresh =>
      (super.noSuchMethod(
            Invocation.getter(#onTokenRefresh),
            returnValue: _i9.Stream<String>.empty(),
          )
          as _i9.Stream<String>);

  @override
  set app(_i5.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i9.Future<_i6.RemoteMessage?> getInitialMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialMessage, []),
            returnValue: _i9.Future<_i6.RemoteMessage?>.value(),
          )
          as _i9.Future<_i6.RemoteMessage?>);

  @override
  _i9.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getAPNSToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAPNSToken, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<String?> getToken({String? vapidKey}) =>
      (super.noSuchMethod(
            Invocation.method(#getToken, [], {#vapidKey: vapidKey}),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<bool> isSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i6.NotificationSettings> getNotificationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationSettings, []),
            returnValue: _i9.Future<_i6.NotificationSettings>.value(
              _FakeNotificationSettings_4(
                this,
                Invocation.method(#getNotificationSettings, []),
              ),
            ),
          )
          as _i9.Future<_i6.NotificationSettings>);

  @override
  _i9.Future<_i6.NotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
    bool? providesAppNotificationSettings = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, [], {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
              #providesAppNotificationSettings: providesAppNotificationSettings,
            }),
            returnValue: _i9.Future<_i6.NotificationSettings>.value(
              _FakeNotificationSettings_4(
                this,
                Invocation.method(#requestPermission, [], {
                  #alert: alert,
                  #announcement: announcement,
                  #badge: badge,
                  #carPlay: carPlay,
                  #criticalAlert: criticalAlert,
                  #provisional: provisional,
                  #sound: sound,
                  #providesAppNotificationSettings:
                      providesAppNotificationSettings,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.NotificationSettings>);

  @override
  _i9.Future<void> setAutoInitEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoInitEnabled, [enabled]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setDeliveryMetricsExportToBigQuery(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setDeliveryMetricsExportToBigQuery, [enabled]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setForegroundNotificationPresentationOptions({
    bool? alert = false,
    bool? badge = false,
    bool? sound = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setForegroundNotificationPresentationOptions,
              [],
              {#alert: alert, #badge: badge, #sound: sound},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [topic]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [topic]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i15.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i15.AppNotification> get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: <_i15.AppNotification>[],
          )
          as List<_i15.AppNotification>);

  @override
  bool get hasPermissions =>
      (super.noSuchMethod(
            Invocation.getter(#hasPermissions),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, int> get stats =>
      (super.noSuchMethod(
            Invocation.getter(#stats),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> show(_i15.AppNotification? notification) =>
      (super.noSuchMethod(
            Invocation.method(#show, [notification]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> showVideoPublished({
    required String? videoTitle,
    required String? nostrEventId,
    String? videoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showVideoPublished, [], {
              #videoTitle: videoTitle,
              #nostrEventId: nostrEventId,
              #videoUrl: videoUrl,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> showUploadComplete({required String? videoTitle}) =>
      (super.noSuchMethod(
            Invocation.method(#showUploadComplete, [], {
              #videoTitle: videoTitle,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> showUploadFailed({
    required String? videoTitle,
    required String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showUploadFailed, [], {
              #videoTitle: videoTitle,
              #reason: reason,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void clearAll() => super.noSuchMethod(
    Invocation.method(#clearAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearOlderThan(Duration? duration) => super.noSuchMethod(
    Invocation.method(#clearOlderThan, [duration]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i15.AppNotification> getNotificationsByType(
    _i15.NotificationType? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsByType, [type]),
            returnValue: <_i15.AppNotification>[],
          )
          as List<_i15.AppNotification>);

  @override
  _i9.Future<void> ensurePermission() =>
      (super.noSuchMethod(
            Invocation.method(#ensurePermission, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendLocal({required String? title, required String? body}) =>
      (super.noSuchMethod(
            Invocation.method(#sendLocal, [], {#title: title, #body: body}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NostrSigner].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrSigner extends _i1.Mock implements _i4.NostrSigner {
  MockNostrSigner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String?> getPublicKey() =>
      (super.noSuchMethod(
            Invocation.method(#getPublicKey, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<_i4.Event?> signEvent(_i4.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#signEvent, [event]),
            returnValue: _i9.Future<_i4.Event?>.value(),
          )
          as _i9.Future<_i4.Event?>);

  @override
  _i9.Future<Map<dynamic, dynamic>?> getRelays() =>
      (super.noSuchMethod(
            Invocation.method(#getRelays, []),
            returnValue: _i9.Future<Map<dynamic, dynamic>?>.value(),
          )
          as _i9.Future<Map<dynamic, dynamic>?>);

  @override
  _i9.Future<String?> encrypt(String? pubkey, String? plaintext) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [pubkey, plaintext]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<String?> decrypt(String? pubkey, String? ciphertext) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [pubkey, ciphertext]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<String?> nip44Encrypt(String? pubkey, String? plaintext) =>
      (super.noSuchMethod(
            Invocation.method(#nip44Encrypt, [pubkey, plaintext]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<String?> nip44Decrypt(String? pubkey, String? ciphertext) =>
      (super.noSuchMethod(
            Invocation.method(#nip44Decrypt, [pubkey, ciphertext]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
