// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/services/video_sharing_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:models/models.dart' as _i3;
import 'package:nostr_client/nostr_client.dart' as _i2;
import 'package:nostr_sdk/event.dart' as _i9;
import 'package:openvine/services/nip17_message_service.dart' as _i4;
import 'package:openvine/services/profile_cache_service.dart' as _i7;
import 'package:openvine/services/user_profile_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNostrClient_0 extends _i1.SmartFake implements _i2.NostrClient {
  _FakeNostrClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNIP17SendResult_1 extends _i1.SmartFake
    implements _i3.NIP17SendResult {
  _FakeNIP17SendResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NIP17MessageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNIP17MessageService extends _i1.Mock
    implements _i4.NIP17MessageService {
  MockNIP17MessageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NostrClient get nostrService =>
      (super.noSuchMethod(
            Invocation.getter(#nostrService),
            returnValue: _FakeNostrClient_0(
              this,
              Invocation.getter(#nostrService),
            ),
          )
          as _i2.NostrClient);

  @override
  _i5.Future<_i3.NIP17SendResult> sendPrivateMessage({
    required String? recipientPubkey,
    required String? content,
    List<List<String>>? additionalTags = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPrivateMessage, [], {
              #recipientPubkey: recipientPubkey,
              #content: content,
              #additionalTags: additionalTags,
            }),
            returnValue: _i5.Future<_i3.NIP17SendResult>.value(
              _FakeNIP17SendResult_1(
                this,
                Invocation.method(#sendPrivateMessage, [], {
                  #recipientPubkey: recipientPubkey,
                  #content: content,
                  #additionalTags: additionalTags,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.NostrConnectSession>);

  @override
  _i7.Future<_i3.AuthResult> waitForNostrConnectResponse({
    Duration? timeout = const Duration(minutes: 2),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForNostrConnectResponse, [], {
              #timeout: timeout,
            }),
            returnValue: _i7.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#waitForNostrConnectResponse, [], {
                  #timeout: timeout,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.AuthResult>);

  @override
  void cancelNostrConnect() => super.noSuchMethod(
    Invocation.method(#cancelNostrConnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void onSignerCallbackReceived() => super.noSuchMethod(
    Invocation.method(#onSignerCallbackReceived, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> refreshCurrentProfile(
    _i9.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> signInAutomatically() =>
      (super.noSuchMethod(
            Invocation.method(#signInAutomatically, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> signInWithDivineOAuth(_i10.KeycastSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithDivineOAuth, [session]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<(bool, String?)> deleteKeycastAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteKeycastAccount, []),
            returnValue: _i7.Future<(bool, String?)>.value((false, null)),
          )
          as _i7.Future<(bool, String?)>);

  @override
  _i7.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<_i4.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
    int? createdAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
              #createdAt: createdAt,
            }),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Future<void> acceptTerms() =>
      (super.noSuchMethod(
            Invocation.method(#acceptTerms, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onAppBackgrounded() => super.noSuchMethod(
    Invocation.method(#onAppBackgrounded, []),
    returnValueForMissingStub: null,
  );

  @override
  void onAppResumed() => super.noSuchMethod(
    Invocation.method(#onAppResumed, []),
    returnValueForMissingStub: null,
  );

  @override
  void onExtendedBackground() => super.noSuchMethod(
    Invocation.method(#onExtendedBackground, []),
    returnValueForMissingStub: null,
  );

  @override
  void onPeriodicCleanup() => super.noSuchMethod(
    Invocation.method(#onPeriodicCleanup, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i6.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i3.UserProfile> get allProfiles =>
      (super.noSuchMethod(
            Invocation.getter(#allProfiles),
            returnValue: <String, _i3.UserProfile>{},
          )
          as Map<String, _i3.UserProfile>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setFunnelcakeAvailable(bool? available) => super.noSuchMethod(
    Invocation.method(#setFunnelcakeAvailable, [available]),
    returnValueForMissingStub: null,
  );

  @override
  void setPersistentCache(_i7.ProfileCacheService? cacheService) =>
      super.noSuchMethod(
        Invocation.method(#setPersistentCache, [cacheService]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.UserProfile? getCachedProfile(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getCachedProfile, [pubkey]))
          as _i3.UserProfile?);

  @override
  bool hasProfile(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#hasProfile, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  bool shouldSkipProfileFetch(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#shouldSkipProfileFetch, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  void markProfileAsMissing(String? pubkey) => super.noSuchMethod(
    Invocation.method(#markProfileAsMissing, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> updateCachedProfile(_i3.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateCachedProfile, [profile]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserProfile?> fetchProfile(
    String? pubkey, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i5.Future<_i3.UserProfile?>.value(),
          )
          as _i5.Future<_i3.UserProfile?>);

  @override
  _i5.Future<void> prefetchProfilesImmediately(List<String>? pubkeys) =>
      (super.noSuchMethod(
            Invocation.method(#prefetchProfilesImmediately, [pubkeys]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchMultipleProfiles(
    List<String>? pubkeys, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchMultipleProfiles,
              [pubkeys],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getDisplayName(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getDisplayName, [pubkey]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getDisplayName, [pubkey]),
            ),
          )
          as String);

  @override
  void removeProfile(String? pubkey) => super.noSuchMethod(
    Invocation.method(#removeProfile, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i3.UserProfile>> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i5.Future<List<_i3.UserProfile>>.value(
              <_i3.UserProfile>[],
            ),
          )
          as _i5.Future<List<_i3.UserProfile>>);

  @override
  void handleProfileEventForTesting(_i9.Event? event) => super.noSuchMethod(
    Invocation.method(#handleProfileEventForTesting, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
