// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/screens/video_metadata_screen_audio_sharing_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i8;

import 'package:keycast_flutter/keycast_flutter.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:models/models.dart' as _i9;
import 'package:nostr_sdk/nostr_sdk.dart' as _i4;
import 'package:openvine/models/pending_upload.dart' as _i2;
import 'package:openvine/models/vine_draft.dart' as _i7;
import 'package:openvine/services/audio_sharing_preference_service.dart'
    as _i12;
import 'package:openvine/services/auth_service.dart' as _i3;
import 'package:openvine/services/upload_manager.dart' as _i5;
import 'package:openvine/services/user_profile_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePendingUpload_0 extends _i1.SmartFake implements _i2.PendingUpload {
  _FakePendingUpload_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrConnectInfo_2 extends _i1.SmartFake
    implements _i4.NostrConnectInfo {
  _FakeNostrConnectInfo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UploadManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadManager extends _i1.Mock implements _i5.UploadManager {
  MockUploadManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  List<_i2.PendingUpload> get pendingUploads =>
      (super.noSuchMethod(
            Invocation.getter(#pendingUploads),
            returnValue: <_i2.PendingUpload>[],
          )
          as List<_i2.PendingUpload>);

  @override
  List<_i2.PendingUpload> get uploadsReadyForProcessing =>
      (super.noSuchMethod(
            Invocation.getter(#uploadsReadyForProcessing),
            returnValue: <_i2.PendingUpload>[],
          )
          as List<_i2.PendingUpload>);

  @override
  Map<String, int> get uploadStats =>
      (super.noSuchMethod(
            Invocation.getter(#uploadStats),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  _i6.Future<void> setUploadTarget(dynamic target) =>
      (super.noSuchMethod(
            Invocation.method(#setUploadTarget, [target]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isBlossomAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBlossomAvailable, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  List<_i2.PendingUpload> getUploadsByStatus(_i2.UploadStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadsByStatus, [status]),
            returnValue: <_i2.PendingUpload>[],
          )
          as List<_i2.PendingUpload>);

  @override
  _i2.PendingUpload? getUpload(String? id) =>
      (super.noSuchMethod(Invocation.method(#getUpload, [id]))
          as _i2.PendingUpload?);

  @override
  _i2.PendingUpload? getUploadByFilePath(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#getUploadByFilePath, [filePath]))
          as _i2.PendingUpload?);

  @override
  _i6.Future<void> markUploadPublished(
    String? uploadId,
    String? nostrEventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markUploadPublished, [uploadId, nostrEventId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markUploadReadyToPublish(
    String? uploadId,
    String? cloudinaryPublicId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markUploadReadyToPublish, [
              uploadId,
              cloudinaryPublicId,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.PendingUpload> startUploadFromDraft({
    required _i7.VineDraft? draft,
    required String? nostrPubkey,
    Duration? videoDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startUploadFromDraft, [], {
              #draft: draft,
              #nostrPubkey: nostrPubkey,
              #videoDuration: videoDuration,
            }),
            returnValue: _i6.Future<_i2.PendingUpload>.value(
              _FakePendingUpload_0(
                this,
                Invocation.method(#startUploadFromDraft, [], {
                  #draft: draft,
                  #nostrPubkey: nostrPubkey,
                  #videoDuration: videoDuration,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.PendingUpload>);

  @override
  _i6.Future<_i2.PendingUpload> startUpload({
    required _i8.File? videoFile,
    required String? nostrPubkey,
    String? thumbnailPath,
    String? title,
    String? description,
    List<String>? hashtags,
    int? videoWidth,
    int? videoHeight,
    Duration? videoDuration,
    _i9.NativeProofData? nativeProof,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startUpload, [], {
              #videoFile: videoFile,
              #nostrPubkey: nostrPubkey,
              #thumbnailPath: thumbnailPath,
              #title: title,
              #description: description,
              #hashtags: hashtags,
              #videoWidth: videoWidth,
              #videoHeight: videoHeight,
              #videoDuration: videoDuration,
              #nativeProof: nativeProof,
            }),
            returnValue: _i6.Future<_i2.PendingUpload>.value(
              _FakePendingUpload_0(
                this,
                Invocation.method(#startUpload, [], {
                  #videoFile: videoFile,
                  #nostrPubkey: nostrPubkey,
                  #thumbnailPath: thumbnailPath,
                  #title: title,
                  #description: description,
                  #hashtags: hashtags,
                  #videoWidth: videoWidth,
                  #videoHeight: videoHeight,
                  #videoDuration: videoDuration,
                  #nativeProof: nativeProof,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.PendingUpload>);

  @override
  _i6.Future<void> pauseUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseUpload, [uploadId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resumeUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeUpload, [uploadId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> retryUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#retryUpload, [uploadId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelUpload, [uploadId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUpload, [uploadId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cleanupCompletedUploads() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupCompletedUploads, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateUploadStatus(
    String? uploadId,
    _i2.UploadStatus? status, {
    String? nostrEventId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUploadStatus,
              [uploadId, status],
              {#nostrEventId: nostrEventId},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateUploadMetadata(
    String? uploadId, {
    String? title,
    String? description,
    List<String>? hashtags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUploadMetadata,
              [uploadId],
              {#title: title, #description: description, #hashtags: hashtags},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cleanupProblematicUploads() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupProblematicUploads, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  Map<String, dynamic> getPerformanceMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceMetrics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.UploadMetrics? getUploadMetrics(String? uploadId) =>
      (super.noSuchMethod(Invocation.method(#getUploadMetrics, [uploadId]))
          as _i5.UploadMetrics?);

  @override
  List<_i5.UploadMetrics> getRecentMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentMetrics, []),
            returnValue: <_i5.UploadMetrics>[],
          )
          as List<_i5.UploadMetrics>);

  @override
  _i6.Future<void> retryUploadWithBackoff(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#retryUploadWithBackoff, [uploadId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i3.AuthState.unauthenticated,
          )
          as _i3.AuthState);

  @override
  _i6.Stream<_i3.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i6.Stream<_i3.AuthState>.empty(),
          )
          as _i6.Stream<_i3.AuthState>);

  @override
  _i6.Stream<_i3.UserProfile?> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i6.Stream<_i3.UserProfile?>.empty(),
          )
          as _i6.Stream<_i3.UserProfile?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i3.AuthenticationSource get authenticationSource =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationSource),
            returnValue: _i3.AuthenticationSource.none,
          )
          as _i3.AuthenticationSource);

  @override
  bool get isRegistered =>
      (super.noSuchMethod(Invocation.getter(#isRegistered), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewIdentity, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#createNewIdentity, [], {
                  #biometricPrompt: biometricPrompt,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i3.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromNsec,
              [nsec],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(
                  #importFromNsec,
                  [nsec],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i3.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromHex,
              [privateKeyHex],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(
                  #importFromHex,
                  [privateKeyHex],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i3.AuthResult> connectWithBunker(String? bunkerUrl) =>
      (super.noSuchMethod(
            Invocation.method(#connectWithBunker, [bunkerUrl]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#connectWithBunker, [bunkerUrl]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i4.NostrConnectInfo> startNostrConnectSession({
    List<String>? relays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startNostrConnectSession, [], {#relays: relays}),
            returnValue: _i6.Future<_i4.NostrConnectInfo>.value(
              _FakeNostrConnectInfo_2(
                this,
                Invocation.method(#startNostrConnectSession, [], {
                  #relays: relays,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.NostrConnectInfo>);

  @override
  _i6.Future<_i3.AuthResult> waitForNostrConnectApproval({
    Duration? timeout = const Duration(seconds: 120),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForNostrConnectApproval, [], {
              #timeout: timeout,
            }),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#waitForNostrConnectApproval, [], {
                  #timeout: timeout,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  void cancelNostrConnectSession() => super.noSuchMethod(
    Invocation.method(#cancelNostrConnectSession, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> refreshCurrentProfile(
    _i10.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> signInAutomatically() =>
      (super.noSuchMethod(
            Invocation.method(#signInAutomatically, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithDivineOAuth(_i11.KeycastSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithDivineOAuth, [session]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<(bool, String?)> deleteKeycastAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteKeycastAccount, []),
            returnValue: _i6.Future<(bool, String?)>.value((false, null)),
          )
          as _i6.Future<(bool, String?)>);

  @override
  _i6.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<_i4.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i6.Future<_i4.Event?>.value(),
          )
          as _i6.Future<_i4.Event?>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AudioSharingPreferenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioSharingPreferenceService extends _i1.Mock
    implements _i12.AudioSharingPreferenceService {
  MockAudioSharingPreferenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAudioSharingEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isAudioSharingEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setAudioSharingEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAudioSharingEnabled, [enabled]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
